**PYTHON CODING CHALLENGE**


SUBMITTED BY:YUVASHRI S

NUMPY QUESTIONS

In [1]:
import numpy as np

1) Create a NumPy array of integers from 10 to 50 (inclusive) and find all even numbers in that array.


In [2]:

arr1 = np.arange(10, 51)
print("1)", arr1[arr1 % 2 == 0])

1) [10 12 14 16 18 20 22 24 26 28 30 32 34 36 38 40 42 44 46 48 50]


2) Generate a 5x5 NumPy array with random integers between 1 and 100, then replace all numbers greater than 50 with the value 50.


In [3]:
arr2 = np.random.randint(1, 101, (5, 5))
print("2) Original:\n", arr2)
print("   Modified:\n", np.where(arr2 > 50, 50, arr2))

2) Original:
 [[51 15 34  3 43]
 [ 6 90 48 59 50]
 [79  4 14 87 26]
 [67 54 17 37 58]
 [62 22 93 41 27]]
   Modified:
 [[50 15 34  3 43]
 [ 6 50 48 50 50]
 [50  4 14 50 26]
 [50 50 17 37 50]
 [50 22 50 41 27]]


3) Create a 1D array of 20 linearly spaced numbers between 0 and 1.


In [4]:
print("3)", np.linspace(0, 1, 20))


3) [0.         0.05263158 0.10526316 0.15789474 0.21052632 0.26315789
 0.31578947 0.36842105 0.42105263 0.47368421 0.52631579 0.57894737
 0.63157895 0.68421053 0.73684211 0.78947368 0.84210526 0.89473684
 0.94736842 1.        ]


4) Given an array [5, 10, 15, 20, 25], repeat each element 3 times.


In [5]:
print("4)", np.repeat([5, 10, 15, 20, 25], 3))


4) [ 5  5  5 10 10 10 15 15 15 20 20 20 25 25 25]


5) Create a 3x3 identity matrix and multiply it by 7.


In [6]:
print("5)\n", np.identity(3) * 7)

5)
 [[7. 0. 0.]
 [0. 7. 0.]
 [0. 0. 7.]]


6) Generate a random 4x4 matrix and compute the sum of each row.


In [7]:
arr6 = np.random.randint(1, 100, (4, 4))
print("6)\n", arr6)
print("   Row Sums:", arr6.sum(axis=1))


6)
 [[98 87 60 18]
 [99 13 75 46]
 [82 62 60 76]
 [90 35 38 99]]
   Row Sums: [263 233 280 262]


7) Given a 2D array, swap its first and last rows.


In [8]:
arr7 = np.random.randint(1, 100, (4, 4))
arr7[[0, -1]] = arr7[[-1, 0]]
print("7)\n", arr7)

7)
 [[49 80  2 55]
 [79 37 96 12]
 [83 66 77  3]
 [89 74 28 13]]


8) Create a 1D array of 100 random numbers sampled from a normal distribution with mean=0 and std=1, then count how many values are positive.


In [9]:
arr8 = np.random.normal(0, 1, 100)
print("8) Positive Count:", np.sum(arr8 > 0))

8) Positive Count: 55


9) Create a 6x6 matrix with 0s on the border and 1s inside.


In [10]:
arr9 = np.ones((6, 6))
arr9[[0, -1], :] = arr9[:, [0, -1]] = 0
print("9)\n", arr9)

9)
 [[0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0.]]


10) Create a 10-element array of zeros and insert the number 5 at the 5th position.


In [11]:
arr10 = np.zeros(10, dtype=int)
arr10[4] = 5
print("10)", arr10)

10) [0 0 0 0 5 0 0 0 0 0]


11) Generate an array of 20 integers and sort it in descending order.


In [12]:
arr11 = np.random.randint(1, 100, 20)
print("11)", np.sort(arr11)[::-1])


11) [98 85 85 82 81 76 72 72 71 41 40 37 37 33 30 30 19 18  8  6]


12) Create a 3x3 matrix filled with numbers from 1 to 9, then flatten it to a 1D array.


In [13]:
print("12)", np.arange(1, 10).reshape(3, 3).flatten())


12) [1 2 3 4 5 6 7 8 9]


13) Replace all odd numbers in an array with -1.


In [14]:
arr13 = np.arange(1, 11)
arr13[arr13 % 2 != 0] = -1
print("13)", arr13)


13) [-1  2 -1  4 -1  6 -1  8 -1 10]


14) Given two arrays [1,2,3] and [4,5,6], stack them vertically and horizontally.


In [15]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
print("14) Vstack:\n", np.vstack((a, b)))
print("    Hstack:", np.hstack((a, b)))

14) Vstack:
 [[1 2 3]
 [4 5 6]]
    Hstack: [1 2 3 4 5 6]


15) Compute the dot product of two 3x3 matrices with random integers.


In [16]:
mat1 = np.random.randint(1, 10, (3, 3))
mat2 = np.random.randint(1, 10, (3, 3))
print("15) Dot Product:\n", np.dot(mat1, mat2))


15) Dot Product:
 [[118  17 125]
 [ 79  12  82]
 [ 72  11  75]]


16) Create an array with shape (2, 3, 4) and find the mean across the last axis.


In [17]:
arr16 = np.random.rand(2, 3, 4)
print("16)\n", arr16.mean(axis=2))

16)
 [[0.59809041 0.39193371 0.5803264 ]
 [0.52004648 0.42250659 0.51750912]]


17) Create a 1D array and split it into 3 equal parts.


In [18]:
print("17)", np.split(np.arange(9), 3))


17) [array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8])]


18) Find unique elements and their counts in an array [1, 2, 2, 3, 4, 4, 4].


In [19]:
arr18 = np.array([1, 2, 2, 3, 4, 4, 4])
u, c = np.unique(arr18, return_counts=True)
print("18) Unique:", u)
print("    Counts:", c)


18) Unique: [1 2 3 4]
    Counts: [1 2 1 3]


19) Given a large array, find the indices of the top 5 maximum values.


In [20]:
arr19 = np.random.randint(1, 1000, 100)
print("19)", arr19.argsort()[-5:][::-1])

19) [17 10 39 60 59]


20) Create a 2D array and normalize it so that all values lie between 0 and 1.


In [21]:
arr20 = np.random.randint(1, 100, (3, 3))
norm = (arr20 - arr20.min()) / (arr20.max() - arr20.min())
print("20)\n", norm)

20)
 [[1.     0.3875 0.7875]
 [0.725  0.     0.525 ]
 [0.025  0.7875 0.225 ]]


PANDAS QUESTION

In [22]:
import pandas as pd



21) Create a DataFrame from a dictionary with columns ‘Name’, ‘Age’, and ‘City’. Add a new column ‘Country’ with the same value for all rows.


In [23]:
data = {'Name': ['Alice', 'Bob', 'Charlie'], 'Age': [25, 32, 28], 'City': ['New York', 'Los Angeles', 'Chicago']}
df = pd.DataFrame(data)
df['Country'] = 'USA'
print(df)


      Name  Age         City Country
0    Alice   25     New York     USA
1      Bob   32  Los Angeles     USA
2  Charlie   28      Chicago     USA


22) Read a CSV file and display the first 5 rows.

In [26]:
df_csv = pd.read_csv('/content/employees (1).csv')
print(df_csv.head())


   EmployeeID          Name  Age           City Department  Salary  \
0         101    John Smith   29       New York         IT   60000   
1         102     Sarah Lee   34        Chicago         HR   55000   
2         103  Michael Chen   41  San Francisco    Finance   75000   
3         104     Ana Kumar   28       New York         IT   58000   
4         105    Ravi Patel   36    Los Angeles      Sales   62000   

    StartDate                Email   Bonus  
0  15-03-2022     john@example.com  1000.0  
1  10-01-2023    sarah@example.com     NaN  
2  20-07-2021  michael@example.com  2000.0  
3  12-05-2023      ana@example.com     NaN  
4  01-11-2020     ravi@example.com  1500.0  


23) Given a DataFrame, drop rows with any missing values.


In [27]:
df_cleaned = df_csv.dropna()
print(df_cleaned)


   EmployeeID          Name  Age           City Department  Salary  \
0         101    John Smith   29       New York         IT   60000   
2         103  Michael Chen   41  San Francisco    Finance   75000   
4         105    Ravi Patel   36    Los Angeles      Sales   62000   
5         106          Raju   23        Chennai         HR   80000   

    StartDate                Email   Bonus  
0  15-03-2022     john@example.com  1000.0  
2  20-07-2021  michael@example.com  2000.0  
4  01-11-2020     ravi@example.com  1500.0  
5  11-10-2022       rr@example.com  3000.0  


24) Filter rows where ‘Age’ is greater than 30.


In [28]:
filtered_df = df[df['Age'] > 30]
print(filtered_df)


  Name  Age         City Country
1  Bob   32  Los Angeles     USA


25) Calculate the mean and median of the ‘Salary’ column.


In [29]:
df['Salary'] = [50000, 60000, 55000]  # Example data
print("Mean:", df['Salary'].mean())
print("Median:", df['Salary'].median())


Mean: 55000.0
Median: 55000.0


26) Sort a DataFrame by the ‘Date’ column in descending order.


In [30]:
df['Date'] = pd.to_datetime(['2023-06-01', '2022-12-15', '2024-01-10'])
sorted_df = df.sort_values(by='Date', ascending=False)
print(sorted_df)


      Name  Age         City Country  Salary       Date
2  Charlie   28      Chicago     USA   55000 2024-01-10
0    Alice   25     New York     USA   50000 2023-06-01
1      Bob   32  Los Angeles     USA   60000 2022-12-15


27) Replace all occurrences of ‘New York’ in the ‘City’ column with ‘NYC’.


In [31]:
df['City'] = df['City'].replace('New York', 'NYC')
print(df)


      Name  Age         City Country  Salary       Date
0    Alice   25          NYC     USA   50000 2023-06-01
1      Bob   32  Los Angeles     USA   60000 2022-12-15
2  Charlie   28      Chicago     USA   55000 2024-01-10


28) Group a DataFrame by ‘Department’ and calculate the average ‘Salary’ for each department.


In [32]:
df['Department'] = ['HR', 'IT', 'IT']
grouped = df.groupby('Department')['Salary'].mean()
print(grouped)


Department
HR    50000.0
IT    57500.0
Name: Salary, dtype: float64


29) Count the number of unique values in the ‘City’ column.


In [33]:
unique_cities = df['City'].nunique()
print("Unique Cities:", unique_cities)


Unique Cities: 3


30) Rename the column ‘DOB’ to ‘Date_of_Birth’.


In [34]:
df['DOB'] = pd.to_datetime(['1990-05-01', '1988-07-12', '1995-09-30'])
df = df.rename(columns={'DOB': 'Date_of_Birth'})
print(df)


      Name  Age         City Country  Salary       Date Department  \
0    Alice   25          NYC     USA   50000 2023-06-01         HR   
1      Bob   32  Los Angeles     USA   60000 2022-12-15         IT   
2  Charlie   28      Chicago     USA   55000 2024-01-10         IT   

  Date_of_Birth  
0    1990-05-01  
1    1988-07-12  
2    1995-09-30  


31) Combine two DataFrames vertically (one below the other).


In [35]:
df1 = pd.DataFrame({'A': [1, 2], 'B': [3, 4]})
df2 = pd.DataFrame({'A': [5, 6], 'B': [7, 8]})
combined_df = pd.concat([df1, df2], ignore_index=True)
print(combined_df)


   A  B
0  1  3
1  2  4
2  5  7
3  6  8


32) Merge two DataFrames on a common column ‘EmployeeID’.


In [36]:
df_left = pd.DataFrame({'EmployeeID': [1, 2], 'Name': ['Alice', 'Bob']})
df_right = pd.DataFrame({'EmployeeID': [1, 2], 'Salary': [70000, 80000]})
merged_df = pd.merge(df_left, df_right, on='EmployeeID')
print(merged_df)


   EmployeeID   Name  Salary
0           1  Alice   70000
1           2    Bob   80000


33) Export a DataFrame to an Excel file.


In [38]:
df.to_excel('OutputOfPython.xlsx', index=False)


34) Given a DataFrame, select only the columns ‘Name’ and ‘Salary’.


In [39]:
selected_df = df[['Name', 'Salary']]
print(selected_df)


      Name  Salary
0    Alice   50000
1      Bob   60000
2  Charlie   55000


35) Create a new column ‘Tax’ as 10% of ‘Salary’.


In [40]:
df['Tax'] = df['Salary'] * 0.10
print(df)


      Name  Age         City Country  Salary       Date Department  \
0    Alice   25          NYC     USA   50000 2023-06-01         HR   
1      Bob   32  Los Angeles     USA   60000 2022-12-15         IT   
2  Charlie   28      Chicago     USA   55000 2024-01-10         IT   

  Date_of_Birth     Tax  
0    1990-05-01  5000.0  
1    1988-07-12  6000.0  
2    1995-09-30  5500.0  


36) Find rows where ‘StartDate’ is after ‘2023-01-01’.


In [41]:
df['StartDate'] = pd.to_datetime(['2022-05-01', '2023-06-10', '2024-03-15'])
after_2023 = df[df['StartDate'] > '2023-01-01']
print(after_2023)


      Name  Age         City Country  Salary       Date Department  \
1      Bob   32  Los Angeles     USA   60000 2022-12-15         IT   
2  Charlie   28      Chicago     USA   55000 2024-01-10         IT   

  Date_of_Birth     Tax  StartDate  
1    1988-07-12  6000.0 2023-06-10  
2    1995-09-30  5500.0 2024-03-15  


37) Replace NaN values in the ‘Bonus’ column with the mean bonus.


In [47]:
df['Bonus'] = [1000, np.nan, 1500]
df['Bonus'] = df['Bonus'].fillna(df['Bonus'].mean())
print(df)


               Name  Age         City Country  Salary       Date Department  \
EmployeeID                                                                    
101           Alice   25          NYC     USA   50000 2023-06-01         HR   
102             Bob   32  Los Angeles     USA   60000 2022-12-15         IT   
103         Charlie   28      Chicago     USA   55000 2024-01-10         IT   

           Date_of_Birth     Tax  StartDate   Bonus  
EmployeeID                                           
101           1990-05-01  5000.0 2022-05-01  1000.0  
102           1988-07-12  6000.0 2023-06-10  1250.0  
103           1995-09-30  5500.0 2024-03-15  1500.0  


38) Set ‘EmployeeID’ as the index of the DataFrame.


In [43]:
df['EmployeeID'] = [101, 102, 103]
df.set_index('EmployeeID', inplace=True)
print(df)


               Name  Age         City Country  Salary       Date Department  \
EmployeeID                                                                    
101           Alice   25          NYC     USA   50000 2023-06-01         HR   
102             Bob   32  Los Angeles     USA   60000 2022-12-15         IT   
103         Charlie   28      Chicago     USA   55000 2024-01-10         IT   

           Date_of_Birth     Tax  StartDate   Bonus  
EmployeeID                                           
101           1990-05-01  5000.0 2022-05-01  1000.0  
102           1988-07-12  6000.0 2023-06-10  1250.0  
103           1995-09-30  5500.0 2024-03-15  1500.0  


39) Drop duplicate rows based on the ‘Email’ column.


In [44]:
df_email = pd.DataFrame({
    'Name': ['Alice', 'Bob', 'Alice'],
    'Email': ['a@example.com', 'b@example.com', 'a@example.com']
})
df_unique = df_email.drop_duplicates(subset='Email')
print(df_unique)


    Name          Email
0  Alice  a@example.com
1    Bob  b@example.com


40) Pivot a DataFrame to show total sales per ‘Product’ per ‘Month’.

In [45]:
sales_df = pd.DataFrame({
    'Product': ['A', 'B', 'A', 'B'],
    'Month': ['Jan', 'Jan', 'Feb', 'Feb'],
    'Sales': [100, 200, 150, 250]
})
pivot_df = sales_df.pivot_table(values='Sales', index='Product', columns='Month', aggfunc='sum')
print(pivot_df)


Month    Feb  Jan
Product          
A        150  100
B        250  200
